version: '2.4'

services:
  app: 
   build: 
    context: .
    dockerfile: Dockerfile
   image: munaelzeer/img_processing:laest
   ports:
     - "3000:3000"
    
   volumes:
     - .:/usr/src/server
     - /usr/src/server/node_modules


   environment:
     - NODE_ENV=development  

